package com.kisanflow.service;
import com.kisanflow.dto.KisanFlowDtos.*;
import com.kisanflow.entity.KisanFlowEntities.*;
import com.kisanflow.repository.KisanFlowRepositories.*;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*; import static com.kisanflow.service.KisanFlowServices.required;
public final class OperationsServices { private OperationsServices() {}
 @Service @RequiredArgsConstructor public static class PaymentService { private final PaymentRepository payments; private final BookingRepository bookings;
  @Transactional public PaymentResponse record(PaymentRequest r){ Booking b=required(bookings.findById(r.getBookingId()),"Booking",r.getBookingId()); Payment p=payments.findByBookingId(b.getId()).orElse(Payment.builder().booking(b).build());p.setAmount(r.getAmount());p.setStatus(r.getStatus());p.setExpectedDate(r.getExpectedDate());p.setActualDate(r.getActualDate());p.setDelayFlag(r.getActualDate()!=null&&r.getActualDate().isAfter(r.getExpectedDate()));return map(payments.save(p)); }
  @Transactional(readOnly=true) public List<PaymentResponse> overdue(){return payments.findByStatusInAndExpectedDateBefore(List.of("pending","processing"),LocalDate.now()).stream().map(this::map).toList();} private PaymentResponse map(Payment p){return PaymentResponse.builder().id(p.getId()).bookingId(p.getBooking().getId()).amount(p.getAmount()).status(p.getStatus()).expectedDate(p.getExpectedDate()).actualDate(p.getActualDate()).delayFlag(p.getDelayFlag()).build();}}
 @Service @RequiredArgsConstructor public static class AlertService { private final CrisisAlertRepository alerts; private final CentreRepository centres; private final AnomalyFlagRepository anomalies; private final BookingRepository bookings;
  @Transactional public AlertResponse create(AlertRequest r){ProcurementCentre c=required(centres.findById(r.getCentreId()),"Centre",r.getCentreId());return map(alerts.save(CrisisAlert.builder().centre(c).alertType(r.getAlertType()).severity(r.getSeverity()).message(r.getMessage()).suggestedAction(r.getSuggestedAction()).status("active").build()));}
  @Transactional(readOnly=true) public List<AlertResponse> active(){return alerts.findByStatusInOrderByCreatedAtDesc(List.of("active","acknowledged")).stream().map(this::map).toList();} @Transactional public AlertResponse resolve(UUID id){CrisisAlert a=required(alerts.findById(id),"Alert",id);a.setStatus("resolved");a.setResolvedAt(OffsetDateTime.now());return map(a);}@Transactional public UUID anomaly(AnomalyRequest r){Booking b=r.getRelatedBookingId()==null?null:required(bookings.findById(r.getRelatedBookingId()),"Booking",r.getRelatedBookingId());return anomalies.save(AnomalyFlag.builder().relatedBooking(b).flagType(r.getFlagType()).description(r.getDescription()).riskLevel(r.getRiskLevel()).status("active").build()).getId();} private AlertResponse map(CrisisAlert a){return AlertResponse.builder().id(a.getId()).centreId(a.getCentre().getId()).alertType(a.getAlertType()).severity(a.getSeverity()).message(a.getMessage()).suggestedAction(a.getSuggestedAction()).status(a.getStatus()).createdAt(a.getCreatedAt()).build();}}
 @Service @RequiredArgsConstructor public static class NotificationService {private final NotificationRepository notifications;private final FarmerRepository farmers;@Transactional public UUID trigger(NotificationRequest r){Farmer f=required(farmers.findById(r.getFarmerId()),"Farmer",r.getFarmerId());return notifications.save(Notification.builder().farmer(f).channel(r.getChannel()).message(r.getMessage()).status("queued").build()).getId();}}
 @Service @RequiredArgsConstructor public static class DigitalDnaService {private final CentreStatsRepository stats;@Transactional(readOnly=true) public CentreStatsResponse get(UUID id){CentreStats s=stats.findByCentreId(id).orElseThrow();return CentreStatsResponse.builder().centreId(id).avgQueueLength(s.getAvgQueueLength()).peakHours(s.getPeakHours()).avgProcessingSpeed(s.getAvgProcessingSpeed()).bottleneckStage(s.getBottleneckStage()).staffEfficiencyScore(s.getStaffEfficiencyScore()).lastUpdated(s.getLastUpdated()).build();}}
}
