package com.kisanflow.controller;
import com.kisanflow.dto.KisanFlowDtos.*; import com.kisanflow.service.KisanFlowServices.*; import com.kisanflow.service.OperationsServices.*; import com.kisanflow.service.AiServiceClient;
import com.kisanflow.integration.FastApiIntegrationClient;
import com.kisanflow.service.QrEntryExitService;
import io.swagger.v3.oas.annotations.*; 
import io.swagger.v3.oas.annotations.tags.Tag; // <-- YEH WALI LINE COMPULSORY ADD KARIYE
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.*;

public final class KisanFlowControllers {private KisanFlowControllers(){}
 @RestController @RequestMapping("/api/v1/farmers") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="Farmers") public static class Farmers {private final FarmerService s;private final com.kisanflow.security.SecurityComponents.Users users;@GetMapping("/me") @PreAuthorize("hasRole('FARMER')") FarmerResponse me(org.springframework.security.core.Authentication auth){return s.get(users.byId((UUID) auth.getPrincipal()).getLinkedFarmer().getId());}@GetMapping @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") List<FarmerResponse> all(){return s.all();}@GetMapping("/{id}") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER') or (hasRole('FARMER') and @securityService.isFarmer(authentication, #id))") FarmerResponse get(@PathVariable UUID id){return s.get(id);}@PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasRole('OFFICER')") FarmerResponse create(@Valid @RequestBody FarmerRequest r){return s.create(r);}@PutMapping("/{id}") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER') or (hasRole('FARMER') and @securityService.isFarmer(authentication, #id))") FarmerResponse update(@PathVariable UUID id,@Valid @RequestBody FarmerRequest r){return s.update(id,r);}@DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasRole('OFFICER')") void delete(@PathVariable UUID id){s.delete(id);}}
 @RestController @RequestMapping("/api/v1/centres") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="Centres") public static class Centres {private final CentreService s;private final BookingService bookings;private final CropPriceService prices;private final DigitalDnaService dna;private final com.kisanflow.service.WeatherReschedulingService weather;@GetMapping List<CentreResponse> all(){return s.all();}@GetMapping("/nearby") List<CentreResponse> nearby(@RequestParam(required = false) Double lat, @RequestParam(required = false) Double lng){return s.all();}@GetMapping("/{id}") CentreResponse get(@PathVariable UUID id){return s.get(id);}@PostMapping @PreAuthorize("hasRole('DISTRICT_OFFICER')") CentreResponse create(@Valid @RequestBody CentreRequest r){return s.create(r);}@PutMapping("/{id}") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") CentreResponse update(@PathVariable UUID id,@Valid @RequestBody CentreRequest r){return s.update(id,r);}@DeleteMapping("/{id}") @PreAuthorize("hasRole('DISTRICT_OFFICER')") void delete(@PathVariable UUID id){s.delete(id);}@GetMapping("/{id}/queue") QueueResponse queue(@PathVariable UUID id){return bookings.queue(id);}@GetMapping("/{id}/bookings/active") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") List<BookingResponse> activeBookings(@PathVariable UUID id){return bookings.centreActive(id);}@GetMapping("/{id}/weather/summary") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") Map<String,Object> weatherSummary(@PathVariable UUID id){return weather.summary(id);}@GetMapping("/{id}/weather/emergency-slots") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") List<EmergencySlotResponse> emergencySlots(@PathVariable UUID id){return weather.slots(id);}@GetMapping("/{id}/crop-prices") List<CropPriceResponse> cropPrices(@PathVariable UUID id){return prices.all(id);}@PutMapping("/{id}/crop-prices") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") CropPriceResponse updateCropPrice(@PathVariable UUID id,@Valid @RequestBody CropPriceRequest r, org.springframework.security.core.Authentication auth){return prices.update(id,r,auth.getName());}@GetMapping("/{id}/digital-dna") CentreStatsResponse dna(@PathVariable UUID id){return dna.get(id);}}
 @RestController @RequestMapping("/api/v1/bookings") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="Bookings and Queue") public static class Bookings {private final BookingService s;private final com.kisanflow.service.WeatherReschedulingService weather;private final com.kisanflow.security.SecurityComponents.Users users;@PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasRole('FARMER')") BookingResponse create(@Valid @RequestBody BookingRequest r){return s.create(r);}@GetMapping("/{id}") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER') or @securityService.isBookingOwner(authentication, #id)") BookingResponse get(@PathVariable UUID id){return s.get(id);}@GetMapping("/farmer/{farmerId}/active") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER') or @securityService.isFarmer(authentication, #farmerId)") List<BookingResponse> active(@PathVariable UUID farmerId){return s.farmerActive(farmerId);}@GetMapping("/farmer/{farmerId}/weather-alerts") @PreAuthorize("hasRole('FARMER') and @securityService.isFarmer(authentication, #farmerId)") List<WeatherAlertResponse> weatherAlerts(@PathVariable UUID farmerId){return weather.alerts(farmerId);}@PostMapping("/{id}/weather/reschedule") @PreAuthorize("hasRole('FARMER')") BookingResponse reschedule(@PathVariable UUID id, org.springframework.security.core.Authentication auth){weather.assertOwner(id, farmer(auth));return weather.reschedule(id);}@PostMapping("/{id}/weather/keep") @PreAuthorize("hasRole('FARMER')") BookingResponse keep(@PathVariable UUID id, org.springframework.security.core.Authentication auth){weather.assertOwner(id, farmer(auth));return weather.keep(id);}@PostMapping("/{id}/weather/cancel") @PreAuthorize("hasRole('FARMER')") BookingResponse cancel(@PathVariable UUID id, org.springframework.security.core.Authentication auth){weather.assertOwner(id, farmer(auth));return weather.cancel(id);}@PatchMapping("/{id}/status") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") BookingResponse advance(@PathVariable UUID id,@Valid @RequestBody StatusUpdateRequest r){return s.advance(id,r);}@GetMapping("/{id}/history") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER') or @securityService.isBookingOwner(authentication, #id)") List<StatusLogResponse> history(@PathVariable UUID id){return s.history(id);}@GetMapping("/{id}/qr") @PreAuthorize("hasRole('FARMER') and @securityService.isBookingOwner(authentication, #id)") Map<String,Object> qr(@PathVariable UUID id){return qrService.bookingQr(id);}private final QrEntryExitService qrService;@SuppressWarnings("unchecked") private UUID farmer(org.springframework.security.core.Authentication auth){return users.byId((UUID) auth.getPrincipal()).getLinkedFarmer().getId();}}
 @RestController @RequestMapping("/api/v1/payments") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="Payments") public static class Payments {
    private final PaymentService s;
    private final com.kisanflow.security.SecurityComponents.Users users;
    @GetMapping("/trader-requirement/{lotId}") @PreAuthorize("hasRole('TRADER')") PaymentResponse getTraderRequirement(@PathVariable UUID lotId, org.springframework.security.core.Authentication auth) {
        UUID actualTraderId = users.byId((UUID) auth.getPrincipal()).getTraderId();
        return s.getTraderPaymentRequirement(actualTraderId, lotId);
    }
    @PostMapping("/initiate-online") @PreAuthorize("hasRole('TRADER')") PaymentResponse initiateOnline(@Valid @RequestBody InitiatePaymentRequest r, org.springframework.security.core.Authentication auth){
        r.setTraderId(users.byId((UUID) auth.getPrincipal()).getTraderId());
        return s.initiateOnline(r);
    }
    @PostMapping("/{id}/online-complete") @PreAuthorize("hasRole('TRADER')") PaymentResponse completeOnline(@PathVariable UUID id, org.springframework.security.core.Authentication auth) {
        UUID actualTraderId = users.byId((UUID) auth.getPrincipal()).getTraderId();
        return s.completeOnline(id, actualTraderId);
    }
    @PostMapping("/offline") @PreAuthorize("hasRole('TRADER')") PaymentResponse submitOffline(@Valid @RequestBody OfflinePaymentRequest r){return s.submitOffline(r);}
    @PostMapping("/{id}/farmer-confirm") @PreAuthorize("hasRole('FARMER')") PaymentResponse farmerConfirm(@PathVariable UUID id, @RequestBody Map<String, Object> body){return s.farmerConfirm(new PaymentActionRequest(id, (Boolean) body.getOrDefault("confirmed", false), (String) body.getOrDefault("remarks", "")));}
    @PostMapping("/{id}/officer-verify") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") PaymentResponse officerVerify(@PathVariable UUID id, @RequestBody Map<String, Object> body){return s.officerVerify(new PaymentActionRequest(id, (Boolean) body.getOrDefault("confirmed", false), (String) body.getOrDefault("remarks", "")));}
    @PostMapping @PreAuthorize("hasRole('OFFICER')") PaymentResponse record(@Valid @RequestBody PaymentRequest r){return s.record(r);}
    @GetMapping("/{id}") PaymentResponse get(@PathVariable UUID id){return s.getPayment(id);}
    @GetMapping("/trader/{traderId}") @PreAuthorize("hasRole('TRADER')") List<PaymentResponse> byTrader(@PathVariable UUID traderId){return s.getPaymentsByTrader(traderId);}
    @GetMapping("/farmer/{farmerId}") @PreAuthorize("hasRole('FARMER')") List<PaymentResponse> byFarmer(@PathVariable UUID farmerId){return s.getPaymentsByFarmer(farmerId);}
    @GetMapping("/pending-verification") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") List<PaymentResponse> pendingVerification(){return s.getPendingVerification();}
    @GetMapping("/overdue") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") List<PaymentResponse> overdue(){return s.overdue();}
 }
 @RestController @RequestMapping("/api/v1/alerts") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="Crisis and anomaly flags") public static class Alerts {private final AlertService s;@PostMapping @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") AlertResponse create(@Valid @RequestBody AlertRequest r){return s.create(r);}@GetMapping List<AlertResponse> active(){return s.active();}@PostMapping("/anomalies") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") Map<String,UUID> anomaly(@Valid @RequestBody AnomalyRequest r){return Map.of("anomalyId",s.anomaly(r));}@PatchMapping("/{id}/resolve") @PreAuthorize("hasRole('DISTRICT_OFFICER')") AlertResponse resolve(@PathVariable UUID id){return s.resolve(id);}}
 @RestController @RequestMapping("/api/v1/notifications") @CrossOrigin(origins="*") @RequiredArgsConstructor public static class Notifications {private final NotificationService s;@PostMapping @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") Map<String,UUID> trigger(@Valid @RequestBody NotificationRequest r){return Map.of("notificationId",s.trigger(r));}}
 @RestController @RequestMapping("/api/v1/ai") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="AI Operations") public static class AiOperations {
    private final FastApiIntegrationClient ai;
    private final com.kisanflow.service.AiOrchestrationService orchestrationService;
    private final com.kisanflow.security.SecurityComponents.Users users;

    @PostMapping("/what-if") public Map<String,Object> whatIf(@RequestBody Map<String,Object> body){return ai.simulate(body).block();}
    
    @PostMapping("/recommend-centres") @PreAuthorize("hasRole('FARMER')")
    public Map<String,Object> recommendCentres(@RequestBody Map<String,Object> request, org.springframework.security.core.Authentication auth) {
        com.kisanflow.entity.KisanFlowEntities.UserAuth u = users.byId((UUID) auth.getPrincipal());
        double lat = Double.parseDouble(request.getOrDefault("latitude", "0").toString());
        double lon = Double.parseDouble(request.getOrDefault("longitude", "0").toString());
        return orchestrationService.recommendCentres(u.getLinkedFarmer().getId(), lat, lon);
    }
    
    @PostMapping("/chat") @PreAuthorize("hasRole('FARMER')")
    public Map<String,Object> chat(@RequestBody Map<String,Object> request, org.springframework.security.core.Authentication auth) {
        com.kisanflow.entity.KisanFlowEntities.UserAuth u = users.byId((UUID) auth.getPrincipal());
        String query = request.getOrDefault("query", "").toString();
        String language = request.getOrDefault("language", "en").toString();
        return orchestrationService.chat(u.getLinkedFarmer().getId(), query, language);
    }
 }
 @RestController @RequestMapping("/api/v1/officer") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="Officer Dashboard") public static class OfficerDashboard {private final CentreService cs;private final AlertService as;private final com.kisanflow.security.SecurityComponents.Users users;@GetMapping("/me") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") Map<String,Object> me(org.springframework.security.core.Authentication auth){com.kisanflow.entity.KisanFlowEntities.UserAuth u = users.byId((UUID) auth.getPrincipal());var m = new java.util.LinkedHashMap<String,Object>();m.put("username", u.getUsername());m.put("role", u.getRole().name());m.put("officerId", u.getOfficerId());m.put("centreId", u.getLinkedCentreId());return m;}@GetMapping("/district-overview") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") Map<String,Object> overview(){var centres=cs.all();long total=centres.size();long operational=centres.stream().filter(c->"active".equalsIgnoreCase(c.getStatus())).count();var m=new java.util.LinkedHashMap<String,Object>();m.put("totalCentres",total);m.put("operationalCentres",operational);m.put("criticalAlertsCount",as.active().size());return m;}}
 /** QR scan + occupancy endpoints. */
 @RestController @RequestMapping("/api/v1/qr") @CrossOrigin(origins="*") @RequiredArgsConstructor @Tag(name="QR Entry/Exit") public static class QrScanner {private final QrEntryExitService qr; private final com.kisanflow.security.SecurityComponents.Users users; @PostMapping("/scan") @PreAuthorize("hasAnyRole('OFFICER','DISTRICT_OFFICER')") QrScanResponse scan(@Valid @RequestBody QrScanRequest req, org.springframework.security.core.Authentication auth){UUID officerId = (UUID) auth.getPrincipal(); UUID centreId = users.byId(officerId).getLinkedCentreId(); return qr.scan(req.getQrId(), centreId);}@GetMapping("/centres/{centreId}/occupancy") OccupancyResponse occupancy(@PathVariable UUID centreId){return qr.occupancy(centreId);}}
}
