import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  hi: {
    appName: "किसान प्रवाह (KisanFlow)",
    tagline: "स्मार्ट कतार एवं कृषि खरीद प्रणाली",
    loginTitle: "किसान लॉगिन / पंजीकरण",
    enterMobile: "अपना 10-अंकीय मोबाइल नंबर दर्ज करें",
    getOtp: "ओटीपी प्राप्त करें",
    verifyOtp: "ओटीपी सत्यापित करें",
    enterOtp: "प्राप्त 4-अंकीय ओटीपी दर्ज करें",
    voiceHint: "आवाज से सहायता के लिए माइक दबाएं",
    name: "किसान का नाम",
    village: "गांव / तहसील",
    crop: "मुख्य फसल",
    wheat: "गेहूं (Wheat)",
    paddy: "धान (Paddy)",
    mustard: "सरसों (Mustard)",
    cotton: "कपास (Cotton)",
    dbtStatus: "डीबीटी बैंक खाता लिंक है",
    saveProfile: "प्रोफ़ाइल सहेजें एवं आगे बढ़ें",
    nearbyCentres: "निकटतम खरीद केंद्र",
    aiRecommendation: "AI स्मार्ट अनुशंसित केंद्र",
    timeSaved: "बचाया गया समय",
    distance: "दूरी",
    liveQueue: "वर्तमान कतार",
    estWait: "अनुमानित प्रतीक्षा",
    bookSlot: "स्लॉट बुक करें",
    selectDate: "तारीख चुनें",
    selectSlot: "समय स्लॉट चुनें",
    quantityQtl: "फसल मात्रा (क्विंटल में)",
    vehicleType: "वाहन का प्रकार",
    tractor: "ट्रैक्टर ट्रॉली",
    truck: "मिनी ट्रक / पिकअप",
    cart: "बैलगाड़ी / अन्य",
    generateToken: "टोकन बनाएं एवं पुष्टि करें",
    tokenGenerated: "आपका डिजिटल टोकन",
    currentServing: "अभी बुलाया जा रहा टोकन",
    yourToken: "आपका टोकन नंबर",
    remainingFarmers: "आपसे आगे किसान",
    startTravelling: "अब घर से निकलें! (Start Travelling Now)",
    startTravellingDesc: "आपकी यात्रा का समय 25 मिनट है। अभी निकलेंगे तो बिना प्रतीक्षा सीधे गेट पर प्रवेश मिलेगा।",
    directions: "रास्ता देखें (GPS Route)",
    listenAudio: "ऑडियो सुनें",
    stepperTitle: "खरीद प्रक्रिया की लाइव स्थिति",
    step1: "टोकन सत्यापन",
    step2: "धर्मकांटा वजन (सकल)",
    step3: "गुणवत्ता एवं नमी परीक्षण",
    step4: "फसल उतराई एवं शुद्ध वजन",
    step5: "खरीद आदेश (J-Form)",
    step6: "डीबीटी बैंक भुगतान",
    stepCompleted: "पूर्ण",
    stepInProgress: "प्रक्रिया में",
    stepPending: "लंबित",
    cropQualityTitle: "फसल गुणवत्ता AI पूर्व-जांच",
    uploadPhoto: "अनाज के दाने की फोटो अपलोड करें",
    analyzing: "AI फसल की जांच कर रहा है...",
    qualityGrade: "अनुमानित गुणवत्ता ग्रेड",
    moistureLevel: "नमी की मात्रा",
    readyToProcure: "खरीद के लिए उपयुक्त (Low Risk)",
    possibleIssue: "नमी अधिक है, धूप में सुखाएं (Possible Issue)",
    notifications: "सूचनाएं एवं अलर्ट",
    voiceAssistant: "किसान साथी AI",
    askAnything: "फसल, मंडी कतार या टोकन के बारे में कुछ भी पूछें...",
  },
  en: {
    appName: "KisanFlow",
    tagline: "AI Smart Queue & Agricultural Procurement Management",
    loginTitle: "Farmer Login / Registration",
    enterMobile: "Enter your 10-digit mobile number",
    getOtp: "Get OTP",
    verifyOtp: "Verify OTP",
    enterOtp: "Enter 4-digit OTP received via SMS",
    voiceHint: "Tap mic for voice assistance in your language",
    name: "Farmer Name",
    village: "Village / Tehsil",
    crop: "Primary Crop",
    wheat: "Wheat",
    paddy: "Paddy",
    mustard: "Mustard",
    cotton: "Cotton",
    dbtStatus: "Aadhaar & DBT Bank Account Linked",
    saveProfile: "Save Profile & Continue",
    nearbyCentres: "Nearby Procurement Centres",
    aiRecommendation: "AI Smart Recommended Centre",
    timeSaved: "Time Saved",
    distance: "Distance",
    liveQueue: "Live Queue",
    estWait: "Est. Wait Time",
    bookSlot: "Book Slot",
    selectDate: "Select Date",
    selectSlot: "Select Time Slot",
    quantityQtl: "Produce Quantity (in Quintals)",
    vehicleType: "Vehicle Type",
    tractor: "Tractor Trolley",
    truck: "Mini Truck / Pickup",
    cart: "Bullock Cart / Other",
    generateToken: "Confirm & Generate Token",
    tokenGenerated: "Your Digital Token",
    currentServing: "Currently Serving Token",
    yourToken: "Your Token Number",
    remainingFarmers: "Farmers Ahead of You",
    startTravelling: "Start Travelling Now!",
    startTravellingDesc: "Your travel time is 25 mins. Leaving now ensures you arrive directly at your slot with zero wait.",
    directions: "Google Maps Route",
    listenAudio: "Listen Audio",
    stepperTitle: "Live Procurement Status Tracker",
    step1: "Gate Token Verification",
    step2: "Gross Weighbridge Weighing",
    step3: "Quality & Moisture Assay",
    step4: "Unloading & Net Weight",
    step5: "Purchase Order (J-Form)",
    step6: "Direct Bank Transfer (DBT)",
    stepCompleted: "Completed",
    stepInProgress: "In Progress",
    stepPending: "Pending",
    cropQualityTitle: "Crop Quality AI Pre-Screening",
    uploadPhoto: "Upload photo of grain sample",
    analyzing: "AI is analyzing moisture & impurities...",
    qualityGrade: "Estimated Quality Grade",
    moistureLevel: "Moisture Content",
    readyToProcure: "Ready for Mandi Procurement (Low Risk)",
    possibleIssue: "Moisture high (>12%), sun drying recommended",
    notifications: "Alerts & Notifications",
    voiceAssistant: "Kisan Saathi AI",
    askAnything: "Ask anything about token status, queue or mandi rates...",
  },
  pb: {
    appName: "ਕਿਸਾਨ ਪ੍ਰਵਾਹ (KisanFlow)",
    tagline: "ਸਮਾਰਟ ਕਤਾਰ ਅਤੇ ਖਰੀਦ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ",
    loginTitle: "ਕਿਸਾਨ ਲੌਗਇਨ / ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    enterMobile: "ਆਪਣਾ 10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    getOtp: "ਓਟੀਪੀ ਪ੍ਰਾਪਤ ਕਰੋ",
    verifyOtp: "ਓਟੀਪੀ ਤਸਦੀਕ ਕਰੋ",
    enterOtp: "ਓਟੀਪੀ ਦਰਜ ਕਰੋ",
    voiceHint: "ਆਵਾਜ਼ ਸਹਾਇਤਾ ਲਈ ਮਾਈਕ ਦਬਾਓ",
    name: "ਕਿਸਾਨ ਦਾ ਨਾਮ",
    village: "ਪਿੰਡ / ਤਹਿਸੀਲ",
    crop: "ਮੁੱਖ ਫ਼ਸਲ",
    wheat: "ਕਣਕ (Wheat)",
    paddy: "ਝੋਨਾ (Paddy)",
    mustard: "ਸਰ੍ਹੋਂ (Mustard)",
    cotton: "ਨਰਮਾ/ਕਪਾਹ (Cotton)",
    dbtStatus: "ਡੀਬੀਟੀ ਬੈਂਕ ਖਾਤਾ ਲਿੰਕ ਹੈ",
    saveProfile: "ਪ੍ਰੋਫਾਈਲ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    nearbyCentres: "ਨੇੜਲੇ ਖਰੀਦ ਕੇਂਦਰ",
    aiRecommendation: "AI ਸਮਾਰਟ ਸਿਫ਼ਾਰਸ਼ ਕੇਂਦਰ",
    timeSaved: "ਬਚਿਆ ਸਮਾਂ",
    distance: "ਦੂਰੀ",
    liveQueue: "ਮੌਜੂਦਾ ਕਤਾਰ",
    estWait: "ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ",
    bookSlot: "ਸਲਾਟ ਬੁੱਕ ਕਰੋ",
    selectDate: "ਤਾਰੀਖ ਚੁਣੋ",
    selectSlot: "ਸਮਾਂ ਸਲਾਟ ਚੁਣੋ",
    quantityQtl: "ਫ਼ਸਲ ਦੀ ਮਾਤਰਾ (ਕੁਇੰਟਲ)",
    vehicleType: "ਵਾਹਨ ਦੀ ਕਿਸਮ",
    tractor: "ਟਰੈਕਟਰ ਟਰਾਲੀ",
    truck: "ਮਿੰਨੀ ਟਰੱਕ",
    cart: "ਹੋਰ",
    generateToken: "ਟੋਕਨ ਪ੍ਰਾਪਤ ਕਰੋ",
    tokenGenerated: "ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਟੋਕਨ",
    currentServing: "ਮੌਜੂਦਾ ਟੋਕਨ",
    yourToken: "ਤੁਹਾਡਾ ਟੋਕਨ ਨੰਬਰ",
    remainingFarmers: "ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ ਕਿਸਾਨ",
    startTravelling: "ਹੁਣੇ ਘਰੋਂ ਨਿਕਲੋ! (Start Travelling)",
    startTravellingDesc: "ਸਫ਼ਰ ਦਾ ਸਮਾਂ 25 ਮਿੰਟ ਹੈ। ਹੁਣੇ ਚੱਲਣ ਤੇ ਸਿੱਧਾ ਗੇਟ ਐਂਟਰੀ ਮਿਲੇਗੀ।",
    directions: "ਰਾਹ ਦੇਖੋ",
    listenAudio: "ਸੁਣੋ",
    stepperTitle: "ਖਰੀਦ ਪ੍ਰਕਿਰਿਆ ਦੀ ਲਾਈਵ ਸਥਿਤੀ",
    step1: "ਟੋਕਨ ਤਸਦੀਕ",
    step2: "ਧਰਮਕੰਡਾ ਵਜ਼ਨ",
    step3: "ਗੁਣਵੱਤਾ ਅਤੇ ਨਮੀ ਜਾਂਚ",
    step4: "ਫ਼ਸਲ ਲੁਹਾਈ ਤੇ ਸ਼ੁੱਧ ਵਜ਼ਨ",
    step5: "ਜੇ-ਫਾਰਮ ਰਸੀਦ",
    step6: "ਡੀਬੀਟੀ ਬੈਂਕ ਭੁਗਤਾਨ",
    stepCompleted: "ਮੁਕੰਮਲ",
    stepInProgress: "ਜਾਰੀ ਹੈ",
    stepPending: "ਬਾਕੀ",
    cropQualityTitle: "ਫ਼ਸਲ ਗੁਣਵੱਤਾ AI ਜਾਂਚ",
    uploadPhoto: "ਦਾਣਿਆਂ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    analyzing: "AI ਨਮੀ ਤੇ ਕੁਆਲਿਟੀ ਜਾਂਚ ਰਿਹਾ ਹੈ...",
    qualityGrade: "ਅੰਦਾਜ਼ਨ ਗ੍ਰੇਡ",
    moistureLevel: "ਨਮੀ ਦੀ ਮਾਤਰਾ",
    readyToProcure: "ਖਰੀਦ ਲਈ ਢੁਕਵਾਂ (Low Risk)",
    possibleIssue: "ਨਮੀ ਵੱਧ ਹੈ, ਸੁਕਾਉਣਾ ਜ਼ਰੂਰੀ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    voiceAssistant: "ਕਿਸਾਨ ਸਾਥੀ AI",
    askAnything: "ਕਤਾਰ ਜਾਂ ਰੇਟ ਬਾਰੇ ਪੁੱਛੋ...",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('kisanflow_lang') || 'hi');

  useEffect(() => {
    localStorage.setItem('kisanflow_lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const speakText = (textToSpeak) => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(textToSpeak || t('appName'));
      utterance.rate = 0.95;
      utterance.pitch = 1.0;
      if (lang === 'hi') utterance.lang = 'hi-IN';
      else if (lang === 'pb') utterance.lang = 'pa-IN';
      else utterance.lang = 'en-IN';
      window.speechSynthesis.speak(utterance);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, speakText, availableLanguages: [
      { code: 'hi', label: 'हिन्दी', flag: '🌾' },
      { code: 'en', label: 'English', flag: '🇬🇧' },
      { code: 'pb', label: 'ਪੰਜਾਬੀ', flag: '🚜' },
    ]}}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
