package com.kisanflow.security;
import com.kisanflow.entity.KisanFlowEntities.*; import com.kisanflow.repository.KisanFlowRepositories.UserAuthRepository;
import io.jsonwebtoken.*; import io.jsonwebtoken.security.Keys; import jakarta.servlet.*; import jakarta.servlet.http.*; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpHeaders; import org.springframework.security.authentication.*; import org.springframework.security.core.*; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.security.core.userdetails.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.*; import org.springframework.web.filter.OncePerRequestFilter;
import javax.crypto.SecretKey; import java.io.IOException; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*; import java.util.concurrent.*;
import org.springframework.security.core.context.SecurityContextHolder;

public final class SecurityComponents {private SecurityComponents(){}
 @Service("securityService") @RequiredArgsConstructor public static class SecurityService {private final Users users; private final com.kisanflow.repository.KisanFlowRepositories.BookingRepository bookings; public boolean isFarmer(Authentication auth, UUID targetFarmerId) {UserAuth u = users.byId((UUID) auth.getPrincipal()); return u.getRole() == Role.FARMER && u.getLinkedFarmer() != null && u.getLinkedFarmer().getId().equals(targetFarmerId);} public boolean isBookingOwner(Authentication auth, UUID bookingId) {Booking b = bookings.findById(bookingId).orElse(null); return b != null && isFarmer(auth, b.getFarmer().getId());}}
 @Component public static class JwtUtil {private final SecretKey key; private final long accessMs,refreshMs; public JwtUtil(@Value("${app.jwt.secret}")String secret,@Value("${app.jwt.access-minutes}")long access,@Value("${app.jwt.refresh-days}")long refresh){key=Keys.hmacShaKeyFor(Base64.getDecoder().decode(secret));accessMs=access*60000;refreshMs=refresh*86400000;} public String access(UserAuth u){return token(u,"access",accessMs);}public String refresh(UserAuth u){return token(u,"refresh",refreshMs);}private String token(UserAuth u,String type,long ttl){return Jwts.builder().subject(u.getId().toString()).claim("role",u.getRole().name()).claim("farmerId",u.getLinkedFarmer()==null?null:u.getLinkedFarmer().getId()).claim("centreId",u.getLinkedCentreId()).claim("type",type).issuedAt(new Date()).expiration(new Date(System.currentTimeMillis()+ttl)).signWith(key).compact();}public Claims parse(String t){return Jwts.parser().verifyWith(key).build().parseSignedClaims(t).getPayload();}public long accessSeconds(){return accessMs/1000;}}
 @Service @RequiredArgsConstructor public static class Users implements UserDetailsService {private final UserAuthRepository repo; public UserDetails loadUserByUsername(String name){UserAuth u=repo.findByUsername(name).orElseThrow(()->new UsernameNotFoundException("Unknown user"));return new org.springframework.security.core.userdetails.User(u.getUsername(),u.getPasswordHash(),List.of(new SimpleGrantedAuthority("ROLE_"+u.getRole().name())));} public UUID userId(String name){return repo.findByUsername(name).orElseThrow(()->new UsernameNotFoundException("Unknown user")).getId();} public UserAuth byId(UUID id){return repo.findById(id).orElseThrow(()->new UsernameNotFoundException("Unknown user"));}public UserAuth farmer(String mobile){return repo.findByLinkedFarmerMobileNumber(mobile).orElseThrow(()->new UsernameNotFoundException("No account for mobile"));}}
 @Component @RequiredArgsConstructor public static class JwtFilter extends OncePerRequestFilter {private final JwtUtil jwt;private final Users users;private final Set<String> blacklist=ConcurrentHashMap.newKeySet();public void blacklist(String t){blacklist.add(t);}@Override protected void doFilterInternal(HttpServletRequest r,HttpServletResponse p,FilterChain c)throws ServletException,IOException{String h=r.getHeader(HttpHeaders.AUTHORIZATION);if(h!=null&&h.startsWith("Bearer ")&&!blacklist.contains(h.substring(7))){try{Claims x=jwt.parse(h.substring(7));if("access".equals(x.get("type"))){UserAuth u=users.byId(UUID.fromString(x.getSubject()));var a=new UsernamePasswordAuthenticationToken(u.getId(),null,List.of(new SimpleGrantedAuthority("ROLE_"+u.getRole().name())));SecurityContextHolder.getContext().setAuthentication(a);}}catch(JwtException|IllegalArgumentException ignored){}}c.doFilter(r,p);}}
 @Service public static class OtpStore {private record Otp(String code,Instant expires,Instant next){}private final Map<String,Otp> values=new ConcurrentHashMap<>();public String send(String mobile){Otp old=values.get(mobile);if(old!=null&&old.next().isAfter(Instant.now()))throw new IllegalStateException("OTP resend cooldown is active");String code=String.format("%06d",ThreadLocalRandom.current().nextInt(1_000_000));values.put(mobile,new Otp(code,Instant.now().plusSeconds(300),Instant.now().plusSeconds(60)));return code;}public boolean verify(String mobile,String code){Otp o=values.remove(mobile);return o!=null&&o.expires().isAfter(Instant.now())&&o.code().equals(code);}}
}
